### ISSUE TITLE
Cucumber Data Table not able to access asMaps method. Exception:java.lang.NoSuchMethodError: cucumber.api.DataTable.asMaps()Ljava/util/List;

### ISSUE THREAD

**Issue by vinaykonke** [cucumber/cucumber-ruby#687]
I have a asMaps method which accpets cuke DataTable and converts to List of Maps. When Cucumber DataTable tries to access cuke.asMaps (where cuke is of DataTable type),then I get an exception which says,  
java.lang.NoSuchMethodError: cucumber.api.DataTable.asMaps()Ljava/util/List; 

This was working properly in 1.1.5 but when I upgraded my cucumber to 1.1.7 this error started showing up.
