### ISSUE TITLE
cucumber2: cannot find tags

### ISSUE THREAD

**Issue by akostadinov** [cucumber/cucumber-ruby#771]
running cucumber like `cucumber features/test/tmp.feature:91` works but running like `cucumber --tags @pry` results in:

```
undefined method `describe_to' for nil:NilClass (NoMethodError)
/usr/local/share/gems/gems/rspec-expectations-2.14.4/lib/rspec/matchers/method_missing.rb:9:in `method_missing'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core/compiler.rb:12:in `feature'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core/gherkin/parser.rb:19:in `document'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core.rb:12:in `block in parse'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core.rb:11:in `each'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core.rb:11:in `parse'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core.rb:23:in `compile'
/home/avalon/.gem/ruby/gems/cucumber-core-1.0.0.beta.3/lib/cucumber/core.rb:31:in `execute'
/home/avalon/.gem/ruby/gems/cucumber-2.0.0.beta.3/lib/cucumber/runtime.rb:71:in `run!'
/home/avalon/.gem/ruby/gems/cucumber-2.0.0.beta.3/lib/cucumber/cli/main.rb:38:in `execute!'
/home/avalon/.gem/ruby/gems/cucumber-2.0.0.beta.3/bin/cucumber:9:in `<top (required)>'
/usr/local/bin/cucumber:23:in `load'
/usr/local/bin/cucumber:23:in `<main>'
```

The same worked in 1.3.x
