### ISSUE TITLE
Cucumber reports empty Background as error wwhen Scenario: statement absent

### ISSUE THREAD

**Issue by Confusion** [cucumber/cucumber-ruby#96]
[Original Lighthouse Ticket 703](https://rspec.lighthouseapp.com/projects/16211/tickets/703-cucumber-reports-empty-background-as-error-wwhen-scenario-statement-absent)

I revived this one, as I just ran into it after upgrading from 0.10.2 to 1.0.0. My case is slightly different from the one in the original ticket: my feature looks like this:

  Background: background_description
    Given ...

  @some_tag
  Scenario: some_description
     When ...

  @some_tag
  Scenario: some_other description
     When ...

I have a profile that excludes 'some_tag' from the run. When I use that, no Scenarios are left in this specific file of features and the originally reported error is raised: 

```
Background: modeler is logged in, has entered a model and sees the model # features/where_clauses.feature:11 
undefined method `tag_names' for nil:NilClass (NoMethodError)
/home/wever/dev/axini/Hare/trunk/vendor/bundle/ruby/1.8/gems/activesupport-3.0.4/lib/active_support/whiny_nil.rb:48:in `method_missing'
/home/wever/dev/axini/Hare/trunk/vendor/bundle/ruby/1.8/gems/cucumber-1.0.0/bin/../lib/cucumber/ast/feature_element.rb:70:in `source_tag_names'
/home/wever/dev/axini/Hare/trunk/vendor/bundle/ruby/1.8/gems/capybara-1.0.0/lib/capybara/cucumber.rb:18:in `Before'
```

This error does not make the build fail. The error is not raised when the build that includes 'some_tag' is built.
