### ISSUE TITLE
undefined method `source_tag_names' on v1.1.5

### ISSUE THREAD

**Issue by hugomaiavieira** [cucumber/cucumber-ruby#227]
After update to v1.1.5 I had this error:

```
undefined method `source_tag_names' for #<Cucumber::Ast::Scenario:0xaed71b4> (NoMethodError)
```
